### ISSUE TITLE
Netherite Tools

### ISSUE THREAD

**Issue by j08** [vvMv/rpgplus#100]
**Description of the bug**
Abilities do not change with netherite tools

**To reproduce**
Tested with Netherite pick only. Right click, nothing happens. Cannot change to vein miner.
Vein miner did not work on Netherite ore either. Tested with Diamond pick.

**Expected behavior**
The abilities should cycle through abilities when right clicked.
The Netherite ore should work with vein miner also.

**Comment by vvMv** [comment]
Thanks for the report, netherite has been added to the default configs 02bb52233e4f93f3e34a403f0aab1871fb10cc27
