### ISSUE TITLE
Title messages

### ISSUE THREAD

**Issue by TadiklCZE** [vvMv/rpgplus#104]
**Description of the feature**
Hey! Can you please add new <title> prefix for messages? It will also have "\n" for subtitle ^^. I would like to use it for levelup messages :)

**Comment by vvMv** [comment]
This can now be done using <title> and <subtitle>, subtitles can be included in the same message that the <title> tag is used. https://github.com/vvMv/rpgplus/commit/8bc9b3fc536bb9ecf6a496fa0310b94a8b5133a1
