### ISSUE TITLE
Attack Ability

### ISSUE THREAD

**Issue by TadiklCZE** [vvMv/rpgplus#105]
**Description of the feature**
You will have a chance to take critical damage. (Passive Ability)
Upgrades:
Chance upgrade
+Damage upgrade

**Comment by vvMv** [comment]
Take critical damage or deal critical damage?

**Comment by TadiklCZE** [comment]
Can I know differences? :D Like a critical damage that is taken from entites taht you hit

**Comment by vvMv** [comment]
Probably just a language thing, if you take damage it means the player gets hurt, if you deal damage, it means the enemy gets hurt. so you want an ability that has a critical hit chance on the enemy

**Comment by TadiklCZE** [comment]
Yup ^^

**Comment by vvMv** [comment]
c67d2248327434adab31d33948eef3ef37fc7927
