### ISSUE TITLE
No DatabaseUtils

### ISSUE THREAD

**Issue by kacperleague9** [vvMv/rpgplus#112]
**Description of the bug**
There is no database utils import.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/34658474/102785991-1ec4b100-439f-11eb-8406-342849288dbd.png)

**Comment by vvMv** [comment]
Can you please provide me with the plugin version and your Spigot username?

**Comment by kacperleague9** [comment]
Hey, i downloaded resource from github to add support for my plugin.

**Comment by kacperleague9** [comment]
then probably github is outdated because on latest code this class doesnt exist

**Comment by vvMv** [comment]
Apologies, I have added these files to VCS
