### ISSUE TITLE
Stamina ability

### ISSUE THREAD

**Issue by j08** [vvMv/rpgplus#35]
**Description of the feature**
This is in most other RPG plugins, but it make sense. As your Stamina ability gains in levels the number of hearts you have should also increase. It makes sense that the fitter you are, the healthier your heart would be.

**Description of alternatives you've considered**
Going to the gym, but I went to Tim Hortons instead.

**Comment by vvMv** [comment]
Will be implementing values to gain half a heart every 5 levels, meaning at level 100 stamina you will have an extra 10 hearts.

Configuration will allow these values to change.

**Comment by vvMv** [comment]
Implementation done using ability points
