### ISSUE TITLE
NPE sent when trying to ChatUtil#sendActionMessage, was switching servers

### ISSUE THREAD

**Issue by foncused** [vvMv/rpgplus#37]
Looks like a stacktrace as a result of a thrown NPE when I was switching servers. Perhaps this happened because I was no longer on the server?

**Comment by foncused** [comment]
https://hatebin.com/qqecthplhq

**Comment by vvMv** [comment]
Looks like lots has been edited since this, can you try the latest version I just posted on spigot? For some reason it had an old jar file and posting the update previously didn't override the new one.
https://www.spigotmc.org/resources/rpgplus.75497/download?version=316927

**Comment by foncused** [comment]
I updated to the latest, guess I'll have to keep an eye on it to see if it happens again.

**Comment by vvMv** [comment]
Bug confirmed to still be present, will attempt at another fix now I know where it's coming from :) Happens when the user is granted experience whilst offline

**Comment by vvMv** [comment]
Fixed afaik
