### ISSUE TITLE
ExperienceGain NPE

### ISSUE THREAD

**Issue by foncused** [vvMv/rpgplus#38]
This looks similar to the last bug report, using the latest version available on Spigot.

https://hatebin.com/uqccyaodwb

**Comment by vvMv** [comment]
I am trying to recreate this issue are you able to recreate it doing anything specific?

**Comment by foncused** [comment]
I am 99% sure it happened for the same exact reason as the other NPE, something to do with no longer being on the server when it fires.

**Comment by vvMv** [comment]
Potentially fixed although check may always return false? 9368e8744d130a16c8e83036ffeeb833db9e9df3
