### ISSUE TITLE
Multi shot

### ISSUE THREAD

**Issue by j08** [vvMv/rpgplus#43]
**Description of the bug**
When multi shot is selected on archery it removes arrows from inventory when you have infinity on bow. 

**To reproduce**
Get bow with infinity and have one arrow in inventory. 
Fire bow with multi shot enabled. 
Bow fires once as you no longer have arrows. 

**Expected behavior**
Arrows should not be removed, or at least it should leave one in inventory.

**Comment by vvMv** [comment]
Will try and provide a fix later tonight thanks

**Comment by vvMv** [comment]
1b8b8c376df3b21575fc2426428a5aaf7719589c
