### ISSUE TITLE
Farming Cocoa Beans and Nether Warts

### ISSUE THREAD

**Issue by j08** [vvMv/rpgplus#44]
**Description of the bug**
Harvesting Cocoa or Nether Warts does not grant experience.

Nether Warts is not in the config and probably should be.

With the Cocoa you have cocoa_beans in the config and not just cocoa. You don't farm the seeds, you farm the cocoa block. Similar to how you farm wheat and not the wheat seeds.

**To reproduce**
Break a cocoa pod or nether warts, no experience is gained.

**Expected behavior**
As both of these are farmed items, both should give experience.

**Comment by vvMv** [comment]
Fixed in plugins default files 590489185f7a6c2a7fcbdea923b0e08e8f84c597
