### ISSUE TITLE
Cacti, sugar cane and bamboo farming. 

### ISSUE THREAD

**Issue by j08** [vvMv/rpgplus#45]
**Description of the bug**
Breaking multiple sections of these plants only grants one experience instance. 

**To reproduce**
Break bottom section of naturally grown sugar cane. Only one instance of experience gained regardless of how many sections were broken above. 

**Expected behavior**
Every non manually planted section of the plant should grant experience when broken.

**Comment by vvMv** [comment]
67296c949e75591172cde11db9c5035a1009760f
