### ISSUE TITLE
Split Shot Ability.

### ISSUE THREAD

**Issue by j08** [vvMv/rpgplus#46]
**Description of the bug**
Split shot removes arrow from inventory when used with a bow that has infinity on it.

**To reproduce**
Place one arrow in inventory and use a bow with infinity enchantment on it. With Split Shot enabled it removes the arrow.

**Expected behaviour**
No arrows should be removed

**Comment by vvMv** [comment]
8a1fad205b6a6617145b19e363454b79380c8fed
