### ISSUE TITLE
Exploding arrow

### ISSUE THREAD

**Issue by j08** [vvMv/rpgplus#47]
**Description of the bug**
Exploding arrow appears to set of an explosion and damage mobs in the correct area as expected. What I am not seeing is any sort of push back to the mobs.

**To reproduce**
Fire arrow with exploding arrow ability selected.

**Expected behaviour**
Mobs should be damaged and pushed back from the source of the explosion as when a creeper goes off, or a meteor from my hat.

**Comment by vvMv** [comment]
I've tested this and don't seem to have any issue with mob pushback, is it perhaps another plugin causing this issue maybe when you're inside your claim? I could see this being prevented when a mob is inside a claim so other people can't push them outside the claim.
