### ISSUE TITLE
Cocoa Ability Points

### ISSUE THREAD

**Issue by j08** [vvMv/rpgplus#48]
**Description of the bug**
Cocoa pods give XP at age 1.

**To reproduce**
Break pod before it is fully grown.

**Expected behavior**
XP should only be given when broken at age 2.

Not Tested: Breaking carrots, potatoes, etc; before fully grown. I would suggest testing.

**Comment by vvMv** [comment]
Fixed here d96809e800f341af1dec380fe7ecf3c8c92d6abb
