### ISSUE TITLE
Remove/reset a player's stats

### ISSUE THREAD

**Issue by foncused** [vvMv/rpgplus#57]
**Description of the feature**
/rpg reset <player>

Just an option to reset/remove a player's stats from the database. It could optionally be broken down into /rpg resetexp or /rpg resetlevel if you like that better.

**Comment by vvMv** [comment]
Nice idea, will implement soon.

**Comment by vvMv** [comment]
952b39d32d5450099b41d75411c2eae70b761374 will be available next release.
The following commands have been added:
reset (to reset attributes and all experience)
resetexperience
setlevels (to set all levels to x in one go)
