### ISSUE TITLE
/back and /homes not working together as expected

### ISSUE THREAD

**Issue by j08** [vvMv/rpgplus#68]
**Description of the bug**
/back not working correctly when using the GUI in /homes

**To reproduce**
1. Start at /spawn.
2. use /home HomeA (where HomeA is one of your homes)
3. use /homes and click on HomeB (where HomeB is a different home)
4. use /back

**Expected behavior**
Player should be moved back to HomeA. The result is you end up back in Spawn.

**Additional context**
It seems when using the /homes gui it is not remembering where you came from. 
Using /home XXXX and then /back always works as expected.

**Comment by vvMv** [comment]
Wrong place, moved to Survilla's GitHub
