### ISSUE TITLE
Fishing Ability - replenish hunger

### ISSUE THREAD

**Issue by j08** [vvMv/rpgplus#69]
**Description of the feature**
This ability will replenish XX amount of hunger (not hearts) when over a water biome (river, ocean, etc).

**Additional context**
Fishermen should never get hungry if they are where fish are, so it should stand to reason that if they are in a water biome it could be assumed they are catching fish and eating them.

I would suggest something along the lines of every 5 minutes the server checks to see who is in a water biome and what there levels in this ability are. Then add .5, 1, 1.5; hunger levels to their hunger bar.

The other way it could be done is to monitor when the player changes biomes and start/stop a timer for that player. Then add their earned hunger levels evry 5 minutes assuming they have earned enough. This seems more complicated than it needs to be though.

**Comment by vvMv** [comment]
Perhaps a simpler approach would be each time a fisherman catches a fish, his hunger gets replenished slightly?

**Comment by vvMv** [comment]
Added in the form of when catching a fish you replenish hunger, requires level 5 by default 514ec2eead838b627c473ebfff9ca7d97722225f
