### ISSUE TITLE
An option to change a design of actionbar and also progressbar

### ISSUE THREAD

**Issue by TadiklCZE** [vvMv/rpgplus#73]
**Description of the feature**
I would like to have this feature, I think it will help most of servers to keep his design. In the config can be something like:
ProgressbarSymbol: |
Progressbar: "&8[&a%progress_symbols%&8]"

And also something like:
ProgressbarEnabled: true/false

**Comment by vvMv** [comment]
Added c7fba2f27f3ba1ad17319bbb501f1036365e32b5
