### ISSUE TITLE
Settings subcommands

### ISSUE THREAD

**Issue by TadiklCZE** [vvMv/rpgplus#94]
**Description of the feature**
I would be really glad if you add commands such as /rpg setsettings %player% <setting> <statement[true/false]>

**Comment by TadiklCZE** [comment]
Maybe would be nice to make statement placeholders. When a player has a statement, you will be able to return its value. (True/False)

**Comment by vvMv** [comment]
Same question as https://github.com/vvMv/rpgplus/issues/95 can you explain which settings you are referring to?

**Comment by vvMv** [comment]
Implemented cd48f28f8566463b61f2f31cf532c130190871b5
