### ISSUE TITLE
Default Settings values

### ISSUE THREAD

**Issue by TadiklCZE** [vvMv/rpgplus#95]
**Description of the feature**
An option to set default values that will players have but joining a server for their first time.

**Comment by vvMv** [comment]
Can you provide some more information on which settings this refers to? Is it weather or not each ability enabled/disabled for the users by default? (basically anything you can toggle in /rpg?)

**Comment by TadiklCZE** [comment]
I would like to disable/Enable settings of notifications by using commands. Also would be nice to make it more customizable by adding this option for abilities settings too ^^.

**Comment by vvMv** [comment]
Default values for new player settings has been added and can be changed in default.yml
